### ISSUE TITLE
Stats methods, survey details and sample protocols

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/UKICER2020#10]
**R1:** _The use of a survey is a sensible approach to gather data for this kind of study quickly. However, more detail on the sampling protocol could be provided,  such as which professional networks, related organisations and various social media channels were used. There is a possibility that there is bias in the 214 CS educators being more or less confident dependent on how they were recruited. It would have been useful to have seen more data about the 71 school, 24 FE and 119 HE respondents, such as their geographic region, gender, position in their organisation. Was data collected on whether respondents were from primary or secondary schools?  It would have been very useful to have seen Figure 1 broken down by educational phase, region etc._

**R1:** _Similarly, it would have been useful to have used the case id for direct quotes (as well as phase), to see if there were specific teachers who contributed more to the qualitative comments._

**R2:** _The justification for the statistical methodology could be clearer, why was quantitative bivariate chi-squared used in preference to other methods? What previous studies have used this methodology?_

**R3:** _Methods, analysis and results are very clearly planned, implemented and clearly described. The section on limitations addresses the key aspects that might have been questioned.  Perhaps the authors could have also recognised that institutions such as the OU have decades of experience in this arena, and considered that in the discussion section._

**R3:** _Could the authors also have given some more attention to their choice of convenience sampling and its background in the way that they did for thematic analysis?  For the latter, what was the inter-rater reliability figure (also note “ensure” rather than “insure”)._

**Comment by CathrynKnight** [comment]
Tempted to ignore first 2- we don't have room for another table of demographics- also there are no responses from primary schools only secondary schools ( I guess we could say this?) 

I don't see how a case id would be useful?

**Comment by CathrynKnight** [comment]
Under 2.3:

Quantitative bivariate chi-square (χ2) analysis of the key variables was conducted in order to determine overall attitudes to online LT&A and whether there were significant differences between those in computer sciences and those in other disciplines.  Chi-square tests were utilised due to the categorical nature of the variables and to to assess whether the observed cell counts are significantly different from the expected cell counts.

(This comment was clearly written by a reviewer that doesn't really understand stats because chi-square is pretty much the only bivariate test you can use with categorical data... put have added a couple more lines)

**Comment by CathrynKnight** [comment]
Under 2.1

We adopted a convenience sampling approach in distributing the Qualtrics survey whereby a link to the survey was advertised via professional networks and related education organisations (for instance the UK’s University and College Union and British Educational Research Association, Higher Education Special Interest Group), in addition to various social media channels (Twitter and LinkedIN, especially) . While the use of convenience sampling does not allow generalisation to a representative population this sampling technique allowed us to document patterns within the observed population, with little time and cost restrictions.

**Comment by CathrynKnight** [comment]
Under 2.3. 

The responses were coded by two researchers to ensure inter-rater reliability (IRR= 0.82).
